### ISSUE TITLE
[node] Carousel not working in FB Messenger

### ISSUE THREAD

**Issue by AmineI** [Microsoft/BotBuilder#1167]
Hi,
Since an update of botbuilder for nodejs, carousels won't work anymore in Messenger, while they're working on Skype for example. The demo-skype example bot is also concerned, and I could reproduce the issue with that bot. Here is a formal bug report : 

**Expected behavior :** Message sent as a carousel when using more than one attachment and the attachmentLayout(builder.AttachmentLayout.carousel)

**Actual behavior :** On Messenger only, the message doesn't appear as a carousel

**Version used :** Latest at the time of writing - 3.2.3 

**How to reproduce :** Try the demo-skype example bot on Messenger.

**Comment by jameslew** [comment]
Hi Aminel,

I just tried this using the demo-skype bot and the Facebook Messenger web client, and got multiple rotating cards in carousel.  Can you be specific as to which Facebook messenger client you're using?

**Comment by AmineI** [comment]
I tried on all of them. Mostly my mobile phone, messenger.com, and the Facebook website.
Will post screenshots ASAP

**Comment by somprabhsharma** [comment]
@AmineI is right, Carousel not working in FB Messenger while its working in Skype, I am facing the similar problem.

**Comment by somprabhsharma** [comment]
It seems that every item inside a carousel must have at least one button to appear as carousel on messenger.

**Comment by muzahmed** [comment]
@AmineI where you able to get it working?

**Comment by AmineI** [comment]
No, I wasn't. Here is a [screenshot](http://i.imgur.com/PhsDfHs.png) of messenger on my computer (website client)
On Skype it's perfectly functional and shows the carousel, but not on messenger.

**Comment by jameslew** [comment]
I think that I missed that you're trying to do this without the buttons.  We're beholden to the rules Facebook requires.  it doesn't look like their API reference says they require the buttons for multiple cards - but that seems to be the behavior.

I'll check with the SDK team to see if they believe otherwise, but this may be a Facebook behavior.

**Comment by AmineI** [comment]
Oh, okay. I thought it wasn't related since, until recently, I've always been able to display carousels, even with only text in attachments.

**Comment by AmineI** [comment]
Indeed, even the featured Poncho bot is using a carousel without buttons, so it's definitely related to bot framework :) .

**Comment by jameslew** [comment]
Okay, will file as a bug and we will investigate.

**Comment by Stevenic** [comment]
Added tom to verify that the channel isn't miss interpreting the facebook rules.

**Comment by slidenerd** [comment]
Well i am also facing the same issue, how about a solution like this
check if the source is facebook, if yes, use source events to deliver a generic template response to messenger , if source is skype, use the hero cards,am gonna try this solution right now and see how that works.

**Comment by slidenerd** [comment]
Nope that solution doesnt work either

**Comment by craigjensen** [comment]
I can confirm that this is a bug in our Facebook channel.  We have a fix in testing and will get it deployed soon.

**Comment by craigjensen** [comment]
Fix was deployed last week.  Please reopen if necessary.

**Comment by AmineI** [comment]
Fantastic, it now works on my side too. Thank you :) !

**Comment by navenduagarwal** [comment]
I am still facing this bug when one item is herocard and another videocard

**Comment by Stevenic** [comment]
@navenduagarwal can you open a new bug? This may be a facebook limitation that they don't allow mixed cards.

**Comment by ankitamadan** [comment]
I am still facing the same issue. My bot works perfectly fine on skype and slack but not on fb messenger.
Please advise
