### ISSUE TITLE
Send message to Customer Representitive

### ISSUE THREAD

**Issue by arunnanjundaswamy** [Microsoft/BotBuilder#2011]
Hi,

I have a scenario in my bot application where I need to redirect the message to the operator (or customer rep) and the interaction will be only between the operator and the customer from now instead of bot sending the messages. 
Reason: may be bot is unable to understand the intent of the user even after multiple user inputs. 

Can someone please guide on how to tackle this.

Regards,
Arun

**Comment by LarsLiden** [comment]
This is a common scenario that I've seen addressed by a number of users in the following manner:

- Build your customer support interface (CSI) (i.e. the side used by your customer support reps) using Direct Line

- Your bot pipes through the all the user messages to the CSI which stores all the conversations. Reps can see a list of all the users interacting with the bot and the history of each of those conversations.

- When escalation to a human is needed, the bot flags one of the conversations needing attention

- Your bot then brokers conversations between the accounts (i.e. Facebook End User <-> Your Bot <-> CSI). Essentially the customer support rep is creating a response, which is being posted by the bot back to the end user

**Comment by piffarettig** [comment]
How could the piping part be implemented? (The part of broadcasting every message the bot receives to the CSI)?

**Comment by piffarettig** [comment]
I am doing the following with still no luck:

Whenever a normal user writes a message, I want to broadcast it to the Customer Representative. For that what I do is:

```
var userAccount = new ChannelAccount("ID_OF_THE_CONVERSATION_BETWEEN_CSI_AND_BOT");
var botAccount = context.Activity.Recipient;
var connector = new ConnectorClient(new Uri(context.Activity.ServiceUrl));
var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount); //botAccount now is the sender, userAccount (CS) is now the recipent.
IMessageActivity messageToSend = Activity.CreateMessageActivity();
messageToSend.From = botAccount;
messageToSend.Recipient = userAccount;
messageToSend.Conversation = new ConversationAccount(id: conversationId.Id);
messageToSend.Text = message.Text;
messageToSend.Locale = "en-Us";
await connector.Conversations.SendToConversationAsync((Activity)message);
```

But the DirectLine CS app is not receiving the message. Is it possible that the ConversationId (ID_OF_THE_CONVERSATION_BETWEEN_CSI_AND_BOT) changes? Because I stored the value of the ConversationId between **Bot <->CSI**, but as I said when I send the message, it never reaches the directline app. 

Some implementation examples of what you proposed would be helpful.

Thanks.

**Comment by ejadib** [comment]
The userAccount needs to be the id of the CSI user, not the id of the conversation. Also, you might try the other way around; the CSI app should be able to read all the conversations going on... I think.

**Comment by piffarettig** [comment]
Cool, thanks again. Yes, but what @LarsLiden states in his proposed solution is the other way. _"Your bot pipes through the all the user messages to the CSI which stores all the conversations. "_

Any sample of implementing that ? How can the CSI app connecting through DirectLine gather all the conversations? 

Thanks

**Comment by ejadib** [comment]
You can't do that; there is no way on DirectLine to get all the conversations. You will need some storage mechanisim in the middle (bot stores active conversation in that storage; csi app read that storage to get conversation ids to use directline)

**Comment by ejadib** [comment]
Another option, not involving the CSI app is having a list of "users" to delegate.. and then you can start a conversation with that users and pass the messages on...

**Comment by piffarettig** [comment]
This is the one I am using right now :) But I still can make work even with  the thing you mentioned   _"The userAccount needs to be the id of the CSI user"_. Where does that ID from the CSI user come right now?

I am using the DirectLineSampleClient (the one we were talking in the other post, in BotBuilder-Samples), where the userId "DirectLineSampleClientUser", but whenever I make the bot send a message to that id it never reaches. So I guess its maybe not that one.

**Comment by piffarettig** [comment]
"This channel does not support this operation" is now the error being thrown, and it fails in the line that creates the conversation from the Bot <-> to the CSI 

` var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);`

Being bot account the ChannelAccount that has the id of the bot and and userAccount the ChannelAccount that has the id of the CSI User

**Comment by ejadib** [comment]
Over which channel are you trying to crate a DirectConversation? What channel/service url?

**Comment by piffarettig** [comment]
Over 'directline'. This is the line that creates the connector.
`var connector = new ConnectorClient(new Uri(context.Activity.ServiceUrl));`

And this is the whole code, pretty similar to what I was doing at the beginning.

```
var userAccount = new ChannelAccount("DirectLineSampleClientUser");
var botAccount = context.Activity.Recipient;
var connector = new ConnectorClient(new Uri(context.Activity.ServiceUrl));
var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);
IMessageActivity messageToSend = Activity.CreateMessageActivity();
messageToSend.From = botAccount;
messageToSend.Recipient = userAccount;
messageToSend.Conversation = new ConversationAccount(id: conversationId.Id);
messageToSend.Text = "I am your father";
messageToSend.Locale = "en-Us";
await connector.Conversations.SendToConversationAsync((Activity)message);
```

**Comment by ejadib** [comment]
DirectLine doesn't support direct conversations. Use CreateConversationAsync()...

**Comment by piffarettig** [comment]
Same Exception being thrown! This is the code right now.

```
var userAccount = new ChannelAccount("DirectLineSampleClientUser");
var botAccount = context.Activity.Recipient;
var connector = new ConnectorClient(new Uri(context.Activity.ServiceUrl));
ConversationParameters convParams = new ConversationParameters();
convParams.Bot = botAccount;
convParams.Members = new List<ChannelAccount>();
convParams.Members.Add(userAccount);
var conversationId = await connector.Conversations.CreateConversationAsync(convParams);  //Here explodes 
```

**Comment by ejadib** [comment]
MMM.. in any case, for the basic scenario of hand off to a human you don't need DirectLine... What exactly are you trying to do with DirectLine?

**Comment by piffarettig** [comment]
The idea of using DirectLine was to provide the experts/customer service an app where they track every conversation and its messages, as well as participate in them. This done in a different GUI, obviously. But I'll probably end up using same channel (for instance Skype), having a user talking to the bot and then the bot redirecting the questions to the expert/CS.

Thanks so much anyway!

**Comment by ejadib** [comment]
For doing that in DirectLine you will need the conversations ids of the users with the bot. Then you can use that id to get the messages from the conversation.

In the other approach, you are suggesting, you are not restricted just to the same channel, you could for example use Slack to talk with the Bot, and redirect questions to the expert/CS in Skype. I've a sample almost ready showing all that interaction that I will be publishing soon.

**Comment by piffarettig** [comment]
That's awesome! If you wan't we can keep in touch to discuss implementation details. I'll probably be carrying out something similar using this approach. Let me know whenever you publish so I can take a look!

**Comment by ejadib** [comment]
See https://github.com/ejadib/handoff-to-human-sample. I will be adding documentation soon.

**Comment by piffarettig** [comment]
Thank you! I'll checking it out over the weekend and tell you my feedback.

**Comment by ubreddy** [comment]
@ejadib  is there a nodejs version that you can direct to? I am new to cs and thought if nodejs sample would be easy to refer to.
