### ISSUE TITLE
All channels acting as though unpublished- error viewing in bot directory

### ISSUE THREAD

**Issue by RossTheMix** [Microsoft/BotBuilder#2412]
I'm not sure if this is a bug in the SDK or not, however my bot has been approved and is marked as "published" here https://dev.botframework.com/bots?id=age_of_consent_bot 
It is also published on Skype and Telegram channels, however it is acting as if it is unpublished (only working on my Skype account, and no-one elses) 
Also when I click on "View in bot directory" it returns the error "An error has occurred." and I cannot find my bot in the directory.

**Comment by carlosscastro** [comment]
Hi @RossTheMix,

There was an issue with the bot directory earlier today. The issue should be fixed now.

Could you please try again? Let me know if that does not work.

**Comment by RossTheMix** [comment]
@carlosscastro Thank you for that. I can now see the bot directory page, however the other issue is still there. 

No matter what I do all channels except skype still act as if my bot isn't published, even though the bot has been approved and I have set all channels to published. 

It works via Skype, so it seems there is no issue with the source of the bot, but the web channel and telegram channel simply accept incoming messages but sent out no responses https://telegram.me/Age_of_consent_bot   
and
https://webchat.botframework.com/embed/age_of_consent_bot?s=lSZzH0qX2Gc.cwA.PaY.4aXLVB4aMZSJavFVTWQB-s5npGaNX_hxa8XfQ0yey48

**Comment by tahsintahsin** [comment]
We have the same issue, our bot is accepted but not visible in either Slack or in bot directory. 
What can we do about it?

**Comment by carlosscastro** [comment]
Can you please send me a link to the bot page in dev.botframework.com?

**Comment by RossTheMix** [comment]
@carlosscastro its https://bots.botframework.com/bot?id=age_of_consent_bot
Is that what you mean?

**Comment by carlosscastro** [comment]
@RossTheMix that is correct. I wanted to do some basic verifications. The bot looks good. I'll assign to our telegram experts to follow up.

**Comment by RossTheMix** [comment]
Thanks @carlosscastro, however it isn't just telegram that isn't working, it's the web channel too.

**Comment by RossTheMix** [comment]
See screenshot of Emulator. 
![image](https://cloud.githubusercontent.com/assets/26311824/23849172/6b3814d0-07d2-11e7-9c05-3a395efff91c.png)

**Comment by tahsintahsin** [comment]
Hello @carlosscastro could you also investigate our bot with app id 71fad264-9fd6-4ecd-808d-becdbc3b7eb1 ? We are suffering from the same issue

**Comment by nwhitmont** [comment]
@RossTheMix are you still experiencing the issue with Bot Directory?

**Comment by RossTheMix** [comment]
@nwhitmont Apologies for the delay in updating. It turns out the issue is with Massively . They do not support any other channel through MS bot network, only Skype. So the issue is on their side. 
Thank you for the time spent helping with this

**Comment by nwhitmont** [comment]
@RossTheMix thanks for the update. I'm glad you found the solution.
