### ISSUE TITLE
Custom Telegram messages

### ISSUE THREAD

**Issue by byrner75** [Microsoft/BotBuilder#283]
Is it possible to send custom telegram messages from Node.js.

I've been trying to call session.send and session.sendMessage with various parameters but no joy. The only type of message I can successfully send is text. 

Here is an example of a call I'm making.

```
session.send( {
    "type": "Message",
    "channelData":
    {
        "method": "sendSticker",
        "parameters":
        {
            "sticker":
            {
                "url": "https://upload.wikimedia.org/wikipedia/commons/3/33/LittleCarron.gif",
                "mediaType": "image/gif"
            }
        }
    }
});

```

**Comment by Stevenic** [comment]
Let me have Tom weigh in. The `channelData` field should work.

**Comment by tomlm** [comment]
You still need to set the normal from, to properties like a normal message and then instead of setting text you pass the channel data

Sent from my tumbs
________________________________

**Comment by Stevenic** [comment]
Tom... I add the From & To under the covers so that should be working.

**Comment by Stevenic** [comment]
So Tom I was just looking at my code and I'm wrong. For the inline reply I'm going to just send what was passed in. For out of band replies then I'm adding all of the other fields on to the envelope. 

```
                        if (res) {
                            this.emit('reply', reply);
                            res.send(200, reply);
                            res = null;
                        } else if (ses.message.conversationId) {
                            // Post an additional reply
                            reply.from = ses.message.to;
                            reply.to = ses.message.replyTo ? ses.message.replyTo : ses.message.from;
                            reply.replyToMessageId = ses.message.id;
                            reply.conversationId = ses.message.conversationId;
                            reply.channelConversationId = ses.message.channelConversationId;
                            reply.channelMessageId = ses.message.channelMessageId;
                            reply.participants = ses.message.participants;
                            reply.totalParticipants = ses.message.totalParticipants;
                            this.emit('reply', reply);
                            post(this.options, endpoint, '/bot/v1.0/messages', reply, (err) => {
                                if (err) {
                                    this.emit('error', err);
                                }
                            });
                        } else {
                            // Start a new conversation
                            reply.from = ses.message.from;
                            reply.to = ses.message.to;
                            this.emit('send', reply);
                            post(this.options, endpoint, '/bot/v1.0/messages', reply, (err) => {
                                if (err) {
                                    this.emit('error', err);
                                }
                            });
                        }
                    });
```

**Comment by byrner75** [comment]
Thanks for the prompt feedback guys. So I've made a couple of changes to setup the conversation and recipient coordinates in my reply however I'm still not getting a message back! The following is my the call I'm making now. I've tried to use the sendMessage method also with a text parameter but still no joy.

```
session.send( {
    type: "Message",
    to: session.message.from,
    from: session.message.to, 
    replyToMessageId: session.message.id,
    conversationId: session.message.conversationId,
    channelConversationId: session.message.channelConversationId,
    channelMessageId: session.message.channelMessageId,
    participants: session.message.participants,
    totalParticipants: session.message.totalParticipants,
    channelData:
    {
        "method": "sendSticker",
        "parameters":
        {
            "sticker":
            {
                "url": "https://upload.wikimedia.org/wikipedia/commons/3/33/LittleCarron.gif",
                "mediaType": "image/gif"
            }
        }
    }
});

```

**Comment by eanders-MS** [comment]
@byrner75 Looks like we had a bug in our handling of channelData for Telegram when the value was a JSON object. I've made it fix and it will be available in the next push to production. We try to do update production at least once a week. If you need a workaround in the meantime, you can send the value as a stringified JSON object.

**Comment by byrner75** [comment]
Thanks for the reply, your suggested workaround works a charm.

**Comment by eanders-MS** [comment]
@byrner75 The fix is now live. You should be able to send channelData as a JSON object. Serialized JSON is still supported.
