### ISSUE TITLE
Telegram bot doesn't respond in group chats

### ISSUE THREAD

**Issue by TexAgg** [Microsoft/BotBuilder#293]
When using the telegram channel, my bot responds to private messages, but when in a group he doesn't respond, even when mentioned.
`/setjoingroups` is enabled, and so is `/setprivacy`, and it is not an inline bot.

**Comment by eanders-MS** [comment]
Verified this is an issue. I've reached out to Telegram for assistance.

**Comment by eanders-MS** [comment]
@TexAgg We've deployed a fix, can you retry? Additionally, Telegram recently made changes to the way bots and privacy work in group chat. Latest behavior summarized here:
https://core.telegram.org/bots#privacy-mode
https://core.telegram.org/bots/faq#what-messages-will-my-bot-get

**Comment by TexAgg** [comment]
Yes it works!

**Comment by yss14** [comment]
For me it still doesn't work. I've updated the bot connector in VS via nuget package manager to v1.1.0 but my bot still doesn't respond in group chats (telegram).

**Comment by eanders-MS** [comment]
@yss14 Is privacy mode enabled for your Telegram bot? (It is enabled by default). If enabled, your bot won't receive all group chat messages, only direct messages.

**Comment by yss14** [comment]
@eanders-MS Thanks, worked for me :)

**Comment by hvilela** [comment]
My bot has privacy mode enabled and it's receiving group messages that starts with '/' but it's not recicing messages that mention him By @UserName. It's part of the same issue?

**Comment by sagarpomal** [comment]
@hvilela I am facing the same issue. Any workarounds?

**Comment by nxmohamad** [comment]
@hvilela did you manage to make it respond to mentions of its name?

**Comment by Niko-La** [comment]
my bot responds to group interactions with private replies... :/

**Comment by lakshykar** [comment]
my bot is not responding on on groups using @botname. But getting response if put / then @botname

any workaround for this issue?

**Comment by telemedotio** [comment]
> my bot is not responding on on groups using @botName. But getting response if put / then @botName
> 
> any workaround for this issue?

when @botName, there should be an array of `entities` in the message body. And one entry of the array is text_entity, which is your bot name. By checking the entities array, the bot can then response correctly.

**Comment by RobertaDelrio** [comment]
I'm not sure it is a related issue but...
My bot responts to group message with a greeting message(in the group chat) that displays keyboard commands. However, when I select a command it responds on the privat chat and not in the group.
Did someone experience something similar and know how to solve it?

**Comment by nekitkee** [comment]
@RobertaDelrio Do you use in response destination chat_id or user_id? (first is correct)

**Comment by RobertaDelrio** [comment]
It is chat_id.
However, I think the problem is related to the use of the InlineKeyboard.

**Comment by StarCanada** [comment]
Folks! I have the same issue! My bot is not working in the group! Any ideas?

**Comment by DharmarajX24** [comment]
How to give BOT access to send message without making it admin? I have privacy enabled

**Comment by EgyptianM** [comment]
I'm facing the same issue now with latest version of telegram.
Bot doesn't respond at all.
Bot is admin, privacy off, not inline and added from bot info window not through group invitation.

**Comment by HugoQuadrado82** [comment]
Hello,

same issue here. Any advice to debug?
He can reply in private, but not in chat group.

The code is really simple:

```
import telegram
from datetime import datetime
import logging
from telegram.ext import Updater, CommandHandler


# Enable logging
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)
logger = logging.getLogger(__name__)

hora = datetime.now().strftime('%H:%M:%S')
data = datetime.now().strftime('%Y-%m-%d')


# Define a function to handle the /hello command
def hello(update, context):
    # Send a message to the user with the text "Hello!"
	user = update.message.from_user
	user_name = user.first_name
	update.message.reply_text('Hello!')
	context.bot.send_message(chat_id=update.message.chat_id, text=f"Hello {user_name}, welcome to the group chat!") 

# Set up the bot and the command handler
updater = Updater('TOKEN', use_context=True)
dispatcher = updater.dispatcher
dispatcher.add_handler(CommandHandler('hello', hello))

# Start the bot
updater.start_polling()
```

Thanks.

**Comment by nirmitsaini1024** [comment]
> I'm facing the same issue now with latest version of telegram. Bot doesn't respond at all. Bot is admin, privacy off, not inline and added from bot info window not through group invitation.

I'm facing the same issue, anyone know how to fix this?  Bot responds in its own chat but doesn't respond at in the group. Bot is admin, privacy off, not inline and added from bot info window not through group invitation.
