### ISSUE TITLE
[Localization] Wrong text encoding in Skype for Business Bot

### ISSUE THREAD

**Issue by Mikhail2k15** [Microsoft/BotBuilder#2943]
Any non-English text are wrong encoded.
Week ago the same code worked as expected. 

## System Information (Required)
* SDK Language: C#>
* SDK Version: 3.8.1
* Development Environment: <AZURE_APP_SERVICE>

## Issue Description
any non-English text are wrong encoded.
Standard Bot Application Visual Studio Template.

## Steps to Reproduce
1. Create Bot using standard Bot Application Template
2. Use Azure App Service to deploy a bot.
3. Type some non-English text in Skype For Business Client for Windows or OWA 

## Actual Results

![image](https://user-images.githubusercontent.com/11201670/27129200-28a951b6-510a-11e7-81d8-0205203cac5c.png)

**Comment by davnewman** [comment]
@Mikhail2k15 Thanks for reporting this issue.  We have fixed the International character encoding bug.  Can you please confirm you are now able to receive the text as expected?

**Comment by dvygolov** [comment]
I still see invalid characters. For example: I try to send a welcome message, with some russian characters. Here's what I get in the emulator. The same goes for Skype or Telegram, when the bot tries to send some questions in russian. 
![image](https://user-images.githubusercontent.com/9249545/30004160-18645c04-90db-11e7-92d4-6feaa07677ac.png)

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.
