### ISSUE TITLE
[Skype] I am trying to publish my demo bot to Skype Channel, by I am getting an error:

### ISSUE THREAD

**Issue by UsamaAslam** [Microsoft/BotBuilder#2979]
i create my bot using bot builder framework in asp.net .Bot work fine in emulator but give me error when i try to publish it with Skype ...

"Your bot did not respond to our Ping request with a success code. Please verify your bot is running and responsive before Publishing your bot. The error received from your bot was: Unauthorized(401), BotAuthenticator failed to authenticate incoming request!"

please help me !!

**Comment by nwhitmont** [comment]
@UsamaAslam Did you register your bot with App ID and password in the Bot Portal at: https://botframework.com?  If so, what is your bot name, bot handle, and Microsoft App ID?

**Comment by UsamaAslam** [comment]
thanks for reply . yes i already register my bot .. here is my bot name :Biz_WeatherBot ,
bot handle :Biz_WeatherBot and my Microsoft id is :6ec9eb2d-1a16-4fdf-903d-d150e93dbed7
and my publish web site link is : https://usamalatestv2.azurewebsites.net/

**Comment by UsamaAslam** [comment]
bot work fine in emulator and Testing in https://botframework.com but when i open  Skype channel and click publish it give me error :
"Your bot did not respond to our Ping request with a success code. Please verify your bot is running and responsive before Publishing your bot. The error received from your bot was: Unauthorized(401), BotAuthenticator failed to authenticate incoming request!"

**Comment by JasonSowers** [comment]
@UsamaAslam do you have your app id and your password in your web config?
```
  <appSettings>
    <add key="MicrosoftAppId" value="YOUR ADD ID" />
    <add key="MicrosoftAppPassword" value="YOUR APP PASSWORD" />
  </appSettings>
```

**Comment by UsamaAslam** [comment]
yes , APP ID and PASSWORD are exactly same as botframework

**Comment by nwhitmont** [comment]
@UsamaAslam I just tested your bot on Skype channel, and it is working normally. See attached screenshot.
<img width="670" alt="screen shot 2017-06-19 at 12 28 55 pm" src="https://user-images.githubusercontent.com/3075047/27302237-139da59e-54eb-11e7-835e-d4273b122859.png">

In order to publish your bot on Skype, you need to provide valid URLs for your Privacy statement and Terms of Service.  You cannot use your bot's messaging endpoint for this. Probably why you are seeing the publish error.
![incorrect privacy and tos urls - biz_weatherbot](https://user-images.githubusercontent.com/3075047/27302347-90e8a45e-54eb-11e7-9568-8c8ce88f92db.png)

**Comment by UsamaAslam** [comment]
still same problem ...
i change the urls but problem not solves . can you guide me what type of url we have to enter in Privacy statement URL and  Terms of use URL ??
![1](https://user-images.githubusercontent.com/29476154/27319344-64f202f4-55aa-11e7-9431-d4d2b1214762.PNG)
![2](https://user-images.githubusercontent.com/29476154/27319345-64f39b32-55aa-11e7-89df-4bd8cac1d9fc.PNG)

**Comment by Cartman720** [comment]
There is an collision between `botbuilder` and microsoft review ping request.
Basically `ChatConnector` says that it can't allow unknown `channelId: test` , it will allow only 
these channels bing,directline,email,facebook,groupme,kik,skype,slack,sms,telegram,webchat.

Here the error

`ERROR: ChatConnector: receive - endorsements validation failure. channelId in req.body: test didn't match the endorsements: bing,directline,email,facebook,groupme,kik,skype,slack,sms,telegram,webchat.`

I think we need to mark this as bug.

**Comment by UsamaAslam** [comment]
okay .. then is their any way to solve this bug / issue ??
can you guide me or inform me how can i remove this bug and add skype channel in my bot ?

thanks

**Comment by Cartman720** [comment]
I don't know, like you I have an issue with this :)
If this is a bug we can't do anything from our side and need to wait for @nwhitmont I think.

**Comment by Cartman720** [comment]
Also I am using NodeJS SDK for this, so I don't think that both NodeJS and ASP.NET SDK's are buggy.
So I think we need PR for both repos or fixing from MS server side

**Comment by nwhitmont** [comment]
There's a problem with the publishing workflow. We are actively working to fix the issue.

**Comment by Cartman720** [comment]
Thanks @nwhitmont !

**Comment by nwhitmont** [comment]
We should have this hotfixed soon, probably in the next 1-2 hour.

**Comment by Cartman720** [comment]
Great!

**Comment by nwhitmont** [comment]
@UsamaAslam @Cartman720 Should be fixed now. Can you verify if its working for you?

**Comment by nwhitmont** [comment]
Fix is deployed

**Comment by UsamaAslam** [comment]
sorry .. problem is not solved still same error on publish click ..

**Comment by UsamaAslam** [comment]
@Cartman720 your problem solved ? or not

**Comment by UsamaAslam** [comment]
@nwhitmont check the screenshot 
![capture12](https://user-images.githubusercontent.com/29476154/27368796-f69b6eb6-566d-11e7-8e04-18bec4678a12.PNG)

**Comment by UsamaAslam** [comment]
Problem solved ..
Thanks

**Comment by UsamaAslam** [comment]
thanks

**Comment by Daddymarto01** [comment]
I still have an issue with this.... 

> Your bot did not respond to our Ping request with a success code. Please verify your bot is running and responsive before Publishing your bot. The error received from your bot was: InternalServerError(500), Internal Server Error  is the error am getting. what could be wrong?

**Comment by praveemich** [comment]
I have the same issue ...

Your bot did not respond to our Ping request with a success code. Please verify your bot is running and responsive before Publishing your bot. The error received from your bot was: InternalServerError(500), Internal Server Error is the error am getting. what could be wrong?
![image_2019_05_16T07_45_50_486Z](https://user-images.githubusercontent.com/8176427/57996450-2b0ecb00-7ae5-11e9-8b9b-4460fd85030f.png)
