### ISSUE TITLE
[Message Formatting] Backtick not working on Slack

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotBuilder#3160]
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.8.4
* Development Environment: LOCALHOST

## Issue Description
When sending a message with the backtick (`) character for code formatting, Slack is ignoring the formatting.

This is working correctly under Teams. Also, using `<code></code>` works in Teams but not in  Slack.

## Code Example
```js
export default function helpLibrary (dependencies) {
  const lib = new builder.Library('help')

  lib.dialog('/', (session, args) => {
    session.endDialog('Help is `disabled`')
  })
  .triggerAction({ matches: 'help' });

  return lib.clone()
}
```
## Expected Behavior
Slack will format the text inside backticks as code.

## Actual Results
Slack ignores the backticks.

**Comment by nrobert** [comment]
I had a look to your issue and can confirm that I got the same problem with C#: I tried single, double and triple backsticks, even HTML encoded:

```C#
await context.PostAsync($: Help is `disabled` (x1) or ``disabled`` (x2) or ```disabled``` (x3), with html: &#96;disabled&#96;");
```

Result is the following: no code formatting / all backsticks removed.
![image](https://user-images.githubusercontent.com/6305666/28364972-f78eac32-6c86-11e7-80c3-df1f4064cdf9.png)

**Comment by nwhitmont** [comment]
@bilby91 Did you try escaping the backtick chars with preceeding slash "\"?

--> ```session.send("Message with \`code formatting\` here");```

**Comment by bilby91** [comment]
@nwhitmont Yes, this doesn't work:

> session.send('foo \`code\` foo');

**Comment by nwhitmont** [comment]
Verified this is a bug.

**Comment by bilby91** [comment]
This is a bug in Microsoft internal Slack connector right?

**Comment by bilby91** [comment]
@nwhitmont Any ETA for a fix ?

**Comment by nwhitmont** [comment]
@bilby91 Just got a fix checked-in today. Should be working shortly.

**Comment by nwhitmont** [comment]
<fixed>

**Comment by santiagodoldan** [comment]
@nwhitmont backticks are still not working in NodeJS/Slack, could be this other issue https://github.com/Microsoft/BotBuilder/issues/3399 related? looks like markdown support isn't working fine for Slack.

**Comment by chinchang** [comment]
Yes, still facing this issue.
