### ISSUE TITLE
Bot stops responding after some time.

### ISSUE THREAD

**Issue by chixcancode** [Microsoft/BotBuilder#4322]
## Bot Info
* SDK Platform:  .Net Framework 4.6
* SDK Version:  3.14
* Active Channels:  Web Chat, Cortana, Skype
* Deployment Environment:  Azure App Service

## Issue Description

After some time, my bot fails to respond.  I cannot say definitively if it's an hour, but is around that time.  The only way to correct issue is to restart service.  I did recently upgrade to the latest version, but not sure if this is the cause.  I also added BotAuth, but have taken it out and issue still occurs.  The error that I see in my event log is this.  

Event time | ‎3‎/‎15‎/‎2018‎ ‎9‎:‎36‎:‎02‎ ‎AM
-- | --
Message | POST to FosterCareAssistant failed: POST to the bot's endpoint failed with HTTP status 500 POST to the bot's endpoint failed with HTTP status 500
Exception type | System.Exception
Failed method | Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__29.MoveNext

{ "message": "An error has occurred.", "exceptionMessage": "Operation returned an invalid status code 'Unauthorized'", "exceptionType": "Microsoft.Bot.Connector.ErrorResponseException", "stackTrace": " at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__8.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__7.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at HHS.ChildWelfareBot.Web.MessagesController.<Post>d__0.MoveNext() in C:\\code\\Code\\FosterCareDemo\\ChildWelfareBot\\Controllers\\MessagesController.cs:line 48\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception 
was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()" }

## Reproduction Steps
1.  Wait for an hour or so
2.
3.

## Expected Behavior
  Bot responds.

**Comment by abilioesteves** [comment]
I'm also having this issue. Sometimes not even restarting the service works and I have to republish the bot. Looks like a token in the connector is getting invalidated after a while.

Just now I've set the App Service as Always On to see if it fixes the issue. If this fixes I'll let you know.

**Comment by abilioesteves** [comment]
No, it didn't work :( I really have no clue how to proceed. I've already searched and nothing works.

**Comment by EricDahlvang** [comment]
We are currently investigating this issue with .NET BotBuilder sdk v3.14

**Comment by EricDahlvang** [comment]
Related issue: https://github.com/Microsoft/BotBuilder/issues/4322

**Comment by cove-ming** [comment]
Just got something similar on the Node.js SDK. I implemented periodic token refresh similar to this https://blog.botframework.com/2017/11/02/optimizing-latency-bot-framework/. However at some point, `getAccessToken` started throwing the following error

```
Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
```

All subsequent calls to bot connector failed after that until I restarted the server.

**Comment by ahattab** [comment]
Having the exact same issue with version 3.14.0.7

**Comment by JakobMadsen717** [comment]
I don't know if it's an hour or perhaps even more. Perhaps related to some internal token that expires after an hour if /api/messages is not called?

In any case I am experiencing the same thing, every morning for example. The service is not "dead", it just doesn't send back responses to questions (mine is a Q&A bot). I can tell from a log that the questions are coming in, I just don't get a reply in e.g. "Test in Web Chat" utility on Azure or DirectLine channel for that matter.

Does anyone know if it helps to downgrade some nuget packages, and if so which ones to downgrade?

**Comment by hpksp** [comment]
@JakobMadsen717 I downgraded one of my bot code instances to 3.13.1 and it's quite stable. Here's my approach;
1. Downgraded first
2. Started the project locally
3. Waited for over one hour
4. Tried to interact with bot through the emulator and it responded.

You can give it a try :)

**Comment by JakobMadsen717** [comment]
Downgrading to Microsoft.Bot.Builder v3.13.1 did not make a difference to me, there must be something else wrong. After downgrading and deploying, I successfully asked the chatbot a few questions, not problems, then left it alone for 1.5-2 hours, and after that it will not respond (until I restart the App Service). Again, the App Service remains "alive", I can see traces like this in Insight:
1‎:‎17‎:‎31‎ ‎PM | Trace @RD00155XXXXXX MessagesController.Post received 'message' with text 'What's the meaning of life?'

It just will not **answer** after a good long sleep.

**Comment by ahattab** [comment]
You will need to downgrade both Microsoft.Bot.Builder and Microsoft.Bot.Connector to 3.13.1 that is working fine with me till now.

**Comment by EricDahlvang** [comment]
The team is actively working a fix for this.  Until we get a release out, please downgrade to v3.13.1.

**Comment by JakobMadsen717** [comment]
After downgrading both Microsoft.Bot.Builder and Microsoft.Bot.Connector to 3.13.1 it seems to work fine again. Thanks ahattab & EricDahlvang!

**Comment by robert4os** [comment]
wow, I was trying for hours to find the error, understand how to debug this... and then it turns out to be the framework itself?!

**Comment by abhishekkant** [comment]
While it is already acknowledged, I wanted to share that even I faced this issue as well.. Maybe 3.14 should have never seen the day of light! I had to even downgrade WindowsAzure.Storage as well to bring in the required Azure Storage state service... 

Any ETA on the release of the fixed version?

**Comment by fredrik-annytab** [comment]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.1.1
* Active Channels: Direct Line
* Deployment Environment: Azure App Service

## Issue Description
I have the same problem, using ASP.NET Core 2.0 and Microsoft.Bot.Connector.AspNetCore 2.0.1.3.

Microsoft.Bot.Connector.ErrorResponseException:
   at Microsoft.Bot.Connector.Conversations+<ReplyToActivityWithHttpMessagesAsync>d__8.MoveNext (Microsoft.Bot.Connector, Version=3.14.1.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Bot.Connector.ConversationsExtensions+<ReplyToActivityAsync>d__7.MoveNext (Microsoft.Bot.Connector, Version=3.14.1.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Annytab.Bot.Accountant.messagesController+<ReplyMessage>d__7.MoveNext (Annytab.Bot.Accountant, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullAnnytab.Bot.Accountant, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\ASP-hemsidor\NetCoreApplications\Annytab.Bot.Accountant\Annytab.Bot.Accountant\Controllers\MessagesController.csAnnytab.Bot.Accountant, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 203)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Annytab.Bot.Accountant.messagesController+<Post>d__5.MoveNext (Annytab.Bot.Accountant, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullAnnytab.Bot.Accountant, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\ASP-hemsidor\NetCoreApplications\Annytab.Bot.Accountant\Annytab.Bot.Accountant\Controllers\MessagesController.csAnnytab.Bot.Accountant, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 120)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Core, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Core, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Core, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Core, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext (Microsoft.AspNetCore.Routing, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__7.MoveNext (Microsoft.AspNetCore.Cors, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext (Microsoft.AspNetCore.Authentication, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware+<Invoke>d__11.MoveNext (Microsoft.AspNetCore.Server.IISIntegration, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware+<Invoke>d__3.MoveNext (Microsoft.AspNetCore.Hosting, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1+<ProcessRequestsAsync>d__2.MoveNext (Microsoft.AspNetCore.Server.Kestrel.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)

## Code Example
<pre>/// &lt;summary&gt;&#10;/// Reply with a message&#10;/// &lt;/summary&gt;&#10;private async Task ReplyMessage(Activity activity, string message)&#10;{&#10;    // Set application credentials&#10;    MicrosoftAppCredentials appCredentials = new MicrosoftAppCredentials(this.options.MicrosoftAppId, this.options.MicrosoftAppPassword);&#10;&#10;    // Create a client&#10;    ConnectorClient client = new ConnectorClient(new Uri(activity.ServiceUrl), appCredentials);&#10;&#10;    // Create a replay&#10;    Activity reply = activity.CreateReply();&#10;&#10;    // Set the message to return&#10;    reply.Text = message;&#10;&#10;    // Reply to the client&#10;    try&#10;    {&#10;        await client.Conversations.ReplyToActivityAsync(reply);&#10;    }&#10;    catch(Exception ex)&#10;    {&#10;        // Log the exception&#10;        this.logger.LogError(ex, $&#34;ReplyToActivityAsync: {reply.Text}&#34;, null);&#10;    }&#10;            &#10;} // End of the ReplyMessage method</pre>

**Comment by ederbond** [comment]
I'm facing the same problem with
Microsoft.Bot.Builder version="3.14.0.7"
Microsoft.Bot.Connector version="3.14.0.7" 

@EricDahlvang any ETA to fix this issue ?

**Comment by JasonSowers** [comment]
We have pushed a new version of the SDK which includes a fix for this issue https://www.nuget.org/packages/Microsoft.Bot.Builder/3.14.1.1

**Comment by aforank** [comment]
I am facing the same issue with v3.15.2.2. After every one hour whenever I try to interact for the first time it throws the same exception "Operation returned an invalid status code 'Unauthorized'". However, when I send the second message it starts working automatically. It's reproducible after every hour. It happens with both webchat and facebook.

**Comment by huyjack178** [comment]
I still got this error with Microsoft.Bot.Connector.AspNetCore v2.0.1.9. Downgrade to 2.0.0.8 still not fix this issue

**Comment by huyjack178** [comment]
I found a solution maybe work for whom got unauthorized exception when bot service is idle. You need to refresh token and pass it to DelegatingHandler when creating BotConnector.

`
var account=new MicrosoftAppCredentials("{MicrosoftAppIdKey}", "{MicrosoftAppPasswordKey}");
var jwtToken=await account.GetTokenAsync();
var connector = new ConnectorClient(new Uri("{serviceUrl}"),handlers:new MyDelegatingHandler(jwtToken));
`
`
public class MyDelegatingHandler : DelegatingHandler
{
    private string _token;
    public MyDelegatingHandler(string token)
    {
        _token = token;
    }

    protected override Task<HttpResponseMessage> SendAsync(
    HttpRequestMessage request, CancellationToken cancellationToken)
    {
        request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _token);
        return base.SendAsync(request, cancellationToken);
    }
}
`

For more detail, please refer to this post 
https://stackoverflow.com/questions/42749982/initiate-a-message-from-bot-to-user-on-botframework

**Comment by hrumhurum** [comment]
The issue with unauthorized exception when bot service is idle still persists with v3.15.3, maybe to somewhat lesser extent.

After 1 or so hour of inactivity bot app encounters such exception:

`Microsoft.Bot.Connector.ErrorResponseException: Operation returned an invalid status code 'Unauthorized'`

when it tries to create a connector client:

``` c#
var connector = new ConnectorClient(new Uri(activity.ServiceUrl));
```

A good workaround for this issue is to keep JWT token afresh. A nice side effect is that the bot's response time improves, as it no longer needs to acquire a fresh JWT token synchronously.

Here is the code that solved the issue for us:

``` c#
sealed class JwtRefreshWorker : IDisposable
{
    CancellationTokenSource _Cts = new CancellationTokenSource();

    public JwtRefreshWorker()
    {
        var appID = ConfigurationManager.AppSettings["MicrosoftAppId"];
        var appPassword = ConfigurationManager.AppSettings["MicrosoftAppPassword"];
        if (!string.IsNullOrEmpty(appID) && !string.IsNullOrEmpty(appPassword))
        {
            var credentials = new MicrosoftAppCredentials(appID, appPassword);
            Task.Factory.StartNew(
                async () =>
                {
                    var ct = _Cts.Token;
                    while (!ct.IsCancellationRequested)
                    {
                        try
                        {
                            // GetTokenAsync method internally calls RefreshAndStoreToken, meaning that the token will automatically be cached at this point and you don’t need to do anything else – the bot will always have a valid token.
                            await credentials.GetTokenAsync().ConfigureAwait(false);
                         }
                         catch (Exception ex)
                         {
                             Trace.TraceError(ex.ToString());
                         }
                         await Task.Delay(TimeSpan.FromMinutes(30), ct).ConfigureAwait(false);
                     }
                 },
                 TaskCreationOptions.LongRunning);
        }
    }

    public void Dispose()
    {
        _Cts.Cancel();
    }
}
```

Then use it in `Global.asax.cs`:

``` c#
JwtRefreshWorker _JwtRefreshWorker;

protected void Application_Start()
{
    _JwtRefreshWorker = new JwtRefreshWorker();
}

protected void Application_End()
{
    _JwtRefreshWorker.Dispose();
    _JwtRefreshWorker = null;
}
```

The given code is based on the work described in https://blog.botframework.com/2017/11/02/optimizing-latency-bot-framework/ article.

**Comment by mitkodi** [comment]
I tried ```BotJwtRefreshWorker``` but it seems doesn't work for me and I can't figure why.
As I can see (from application insights) during the bot activity periods it requests a token (calls https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token) almost every 10 minutes. And each call is a part of request to the bot, not a standalone output request (from  ```BotJwtRefreshWorker```).
So I don't understand:
1. Why it requests a new token every 10 minutes in case the tokens expire in 3600 seconds.
2. Why there is no any requests for tokens during inactive periods/why there is no any standalone output requests for tokens respectively.

(*the bot.builder's version is 3.16.0 and the application pool's idle-timeout is 0*)

![pic1](https://user-images.githubusercontent.com/5601143/45755928-4957ba80-bc28-11e8-9550-f7f391a552d9.jpg)
![pic2](https://user-images.githubusercontent.com/5601143/45755944-4eb50500-bc28-11e8-9553-5c5cf8dc25fc.jpg)

**Comment by EricDahlvang** [comment]
@mitkodi The team does not actively monitor closed issues.  Please open a new issue if you are still experiencing problems
