### ISSUE TITLE
Directline API returning 500 internal server error

### ISSUE THREAD

**Issue by sharmadine** [Microsoft/BotBuilder#4540]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.1
* Active Channels: Skype, Direct Line (Webchat) 
* Deployment Environment: Azure Bot Service

## Issue Description
Getting different errors from directline API endpoint today. The bot is not performing and frequently stops responding to user's request.

Please find below one of the error log entry. We are running the bot in production for a few months now and are observing such errors for the first time. Please help.

```
Error: POST to 'https://directline.botframework.com/v3/conversations/EPxxxxxxxxxY/activities/EPxxxxxxxxxY%7C0000000' failed: [500]  
    at Request._callback (/usr/src/app/node_modules/bot-services/node_modules/botbuilder/lib/bots/ChatConnector.js:559:46)
    at Request.self.callback (/usr/src/app/node_modules/bot-services/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/src/app/node_modules/bot-services/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/bot-services/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by sharmadine** [comment]
Thanks for your response. Please find below the Information:

APP_ID: ad684b78-c94f-4c5e-be5d-8bcb3ccd9c37
Bot_Handle: the handle contains organisation name and won't be able to share on public platform. Is there an email id where I can send it out?

**Comment by sharmadine** [comment]
Thanks for the update. We have implemented custom state for quite sometime. We will a relook again. It's bit of surprise that we got 500 errors but you couldn't see it in logs. Not sure how to get to the root cause.

**Comment by sharmadine** [comment]
Thanks for the update. We have implemented custom state for quite sometime. We will a relook again. It's bit of surprise that we got 500 errors but you couldn't see it in logs. Not sure how to get to the root cause.

**Comment by EricDahlvang** [comment]
@sharmadine @Gawashi-se0 

Are either you still experiencing this issue with the latest bot.builder library? https://www.npmjs.com/package/botbuilder

**Comment by sharmadine** [comment]
Not facing the issue now but we still couldn't find the reason of those failures.

**Comment by EricDahlvang** [comment]
I apologize, but I also do not know the reason for the failures.  Since the issue is no longer occurring, I'm going to close this.  Please open a new issue if you experience any further problems.
