### ISSUE TITLE
Token not being cached for bot authentication with users and magic numbers don't work

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotBuilder#4899]
Hello,

I am getting the same problem as my previous one with token no caching as it should. This happens in the emulator though. It was able to hold the cached token before, but now it doesn't. This happened before the following issue happened.

The other issue is that whenever I paste the authentication number to chat, the bot tells me an error message as follow:

![image](https://user-images.githubusercontent.com/5460795/43168100-00615c22-8f6a-11e8-86df-a255e8212da9.png)

**Comment by JasonSowers** [comment]
Are you using teams?  If not what channel?

**Comment by Rykimaruh** [comment]
@JasonSowers , yes I am using Teams

**Comment by JasonSowers** [comment]
You have to type in the code for teams, copying and pasting will make the text input be like “\r\n804230\n” or something similar. I wrote a refer that can handle this programmatically I can post shortly.

**Comment by JasonSowers** [comment]
This is just one way to handle this in your code. You could probably find a better way of doing this.

In my messages controller I put a check for the magic code copy paste like this:
```cs
            if (activity.Type == ActivityTypes.Message)
            {
                if (activity.ChannelId == ChannelIds.Msteams && activity.Text.StartsWith("\r\n"))
                {
                        activity.Text = CustomCode.SanatizeMagicCodeForTeams(activity.Text);
                }
                await Conversation.SendAsync(activity, () => new RootDialog());
            }
```
Then I wrote this simple static class to handle it:

```cs
    public static class CustomCode
    {
        public static Dictionary<string, string> RedirectDictionary; 
        public static string SanatizeMagicCodeForTeams(string magicCode)
        {
            Regex regex = new Regex(@"\r\n(\d{6})\n");
            var match = regex.Match(magicCode);
            if (match.Success)
            {
                magicCode = magicCode.Substring(2, 6);
            }
            return magicCode;
        }
    }
```

**Comment by JasonSowers** [comment]
@Rykimaruh let me know if that helps

**Comment by Rykimaruh** [comment]
@JasonSowers , the only thing missing is the CustomeCode ion message controller

Error: The name "CustomCode" does not exist in the current context

**Comment by Rykimaruh** [comment]
@JasonSowers  it works! Thank you!

Were you able to check up on other issue pertaining the cached token and the emulator?

**Comment by Rykimaruh** [comment]
"I am getting the same problem as my previous one with token no caching as it should. This happens in the emulator though. It was able to hold the cached token before, but now it doesn't. This happened before the following issue happened." 

It would seem token caching is having issues again. Can this be verified?

**Comment by JasonSowers** [comment]
Ahh yes, this issue resurfaced, it should be fixed now.  Someone else pointed this out earlier and I was able to get the team to deploy a temporary fix until we have a more permanent one in our next release.

If you start seeing trouble with the emulator and you have had it running for a while(~8 hours), restart the emulator.  Then emulator uses ngrok, and ngrok sessions expire after 8 hours.

**Comment by Rykimaruh** [comment]
@JasonSowers , it was working for a short while, but it seems the issue came back once again.

**Comment by JasonSowers** [comment]
It should be fixed again, it will be permanently fixed in our next deployment.  Thanks for reporting.

**Comment by JasonSowers** [comment]
Going to close this issue.  Please open a new one if you experience anything else we can help with.
