### ISSUE TITLE
Random ChatConnector errors with Slack (v3.0.1, Node)

### ISSUE THREAD

**Issue by thingista** [Microsoft/BotBuilder#657]
Finally managed to upgrade to 3.0.1 and it *mostly* works:

- Skype works well
- Slack works most of the time, but sometimes (and randomly as far as I can tell) I see the following message in the log:
`ERROR: ChatConnector: receive - invalid token. Check bots app ID & Password.`

I am using the "Hello World" code example from the doc (http://docs.botframework.com/en-us/node/builder/overview/#navtitle) and as such I doubt the problem is in my code. Besides, the fact it's random makes it very hard to debug.

Is anyone else seeing this?

**Comment by javi-jamaa** [comment]
I have the same problem, I'm using the node framework v 3.0.1.

**Comment by thingista** [comment]
I haven't touched the code, nor the deployment stack, and I am now seeing a different error message in the console. It now says:

`SyntaxError: Unexpected token u`

And in Slack, the bots reply with this message:

> Oops. Something went wrong and we need to start over.

So I guess the problem is with the Connector system itself and it's being tweaked as we speak?

cc @Stevenic

**Comment by DirkSonguer** [comment]
Same problem here, after updating the bot from v1 (where Slack and web chat worked flawlessly) to v3, I noticed that Slack and Web Chat stopped working live. It seems like for some reason Slack and web chat do not authenticate themselves correctly: "_ERROR: ChatConnector: receive - invalid token. Check bots app ID & Password._"

Skype works as intented :(

**Comment by thingista** [comment]
It looks like it has been fixed now. Slack is working fine - and others have reported the same thing. So I will close this.

**Comment by DirkSonguer** [comment]
Well, not really, I'm still having there issues. However when trying our different things, I noticed the following:

When the app is hosted on a shared Azure instance (F1 Free or D1 Shared), then the channels randomly can't connect and I get "ERROR: ChatConnector: receive - invalid token. Check bots app ID & Password." from my bot app (node). When I scale up to a B1 Basic or above, everything works fine.

So if you're running into the connection issue, check what kind of instance you're running on and try scaling up.
