### ISSUE TITLE
Getting 500 InternalServerError using NodeJs Sample

### ISSUE THREAD

**Issue by yeelynn** [Microsoft/BotBuilder#669]
Hi,

I encountered the error InternalServerError when I am testing the NodeJS sample "demo-skype"
![aaa](https://cloud.githubusercontent.com/assets/16470517/16794206/e37b3136-4908-11e6-9a95-3c73e139fc15.png)

The emulator also shows 500 InternalServerError.

Steps I have taken:
1) Deployed the "demo-skype" sample into Azure (without changes to the code) using Azure CLI & git command
2) Registered a new bot in Microsoft Bot Framework to get the appId & appPassword.
3) Set the App Settings in Azure like so:
![aaa](https://cloud.githubusercontent.com/assets/16470517/16794524/d4b0b714-490a-11e6-837f-c083d52ab678.png)

Note that when I use VisualStudio to create sample bot application and publish to Azure + create new bot, it can perform successfully in emulator/skype etc

So I was wondering am I doing something wrong using NodeJS?

Any help is appreciated :)

**Comment by brene** [comment]
Usually this happens, when you forgot to add "/api/messages" to your bot endpoint. Since the example uses Restify, and is listening to POST request to "/api/messages". You should also add "/api/messages" to your base URL. Hope this helps.

**Comment by danmarshall** [comment]
Hi @yeelynn this may have been a transient error in the bot framework that has been fixed by now. Please open a new issue if you see this again, thanks.

**Comment by twgcriot** [comment]
This error persists. 

I am using node.js and when using the emulator and ngrok to connect to my bot deployed on Azure i still get the "InternalServerError"

**Comment by jaskiratr** [comment]
The error persists even after adding "/api/messages" to the base URL.

**Comment by nixxholas** [comment]
second to that

**Comment by kylepolich** [comment]
Yup, I am having this problem with the very basic hello world code provided by Microsoft.  Seems like Bot Framework might now be a legacy project?  Why wouldn't the basic examples work when deploying to Azure.

**Comment by nwhitmont** [comment]
@kylepolich You are commenting on a closed issue. Please open a new issue if you have a problem or question, so that we may better assist you.
