### ISSUE TITLE
WebChat responses goes out of sync and the ticker stops

### ISSUE THREAD

**Issue by rohanar** [Microsoft/BotBuilder#965]
Playing with a simple bot on WebChat shows that the responses go out of sync with the requests. Network activities in chrome developer tools show that the "ticker" has stopped when this happens.

How to replicate:

My bot is here: https://webchat.botframework.com/embed/calmacbotv3?s=RJq9xTtB2OY.cwA.yS0.bHstdR5W1qKfnEtlMr2BJ3qhyRYrnjhqxZyE1tWrfpk

Try the commands/utterances "allroutes" and "allports" alternatively. After few attempts, you will miss to receive a response. Thereafter you get the previous response for the new command/utterance. When this happens the ticker has stopped.

**Comment by danmarshall** [comment]
Hi @rohanar , it seemed to respond to me without failing.

**Comment by rohanar** [comment]
Thanks  @danmarshall for taking a look.  It definitely has an issue though. As I mentioned in my first post, you need to try it about 7-10 times to see the issue. Using the commands/utterances "allroutes" and "allports" alternatively helps you identify if you get the correct response...

**Comment by danmarshall** [comment]
I see, the polling activity ceases, then webchat no longer shows bot's response.

**Comment by rohanar** [comment]
Any chance someone fixing this!

**Comment by dandriscoll** [comment]
Hi @rohanar, sorry for the delay. We do have this fixed and should have the fix available in a few days. Thanks for reporting the issue.

**Comment by danmarshall** [comment]
Hi @rohanar can you verify that this issue is resolved for you?

**Comment by rohanar** [comment]
Much better - Thanks. 
However occasionally, it delays sending a response until you issue a subsequent/next command/utterance. When this happens it returns both the response to the new and the previous commands together. So the responses won't go missing now. 
This issue leads to an error when your utterance is a reply to a prompt. This happens arbitrarily and I can't give you exact sequence of commands/utterances to reproduce it. I was playing with the following utterances/commands  in random order. You will notice at some point that you won't get a response,  and your next command with bring back both responses...

allroutes
allports
route 5 monday timetable
route 7 tuesday timetable

**Comment by dandriscoll** [comment]
Yes, it looks like this is still a problem under somewhat more specific conditions. Thanks for paying close attention!

**Comment by dandriscoll** [comment]
Hi @rohanar, I have this fixed locally and will have it deployed sometime next week. Thanks again for reporting it.

**Comment by snbuchholz** [comment]
Hi, I had similar issues on Slack in addition to webchat. Is your fix only for webchat?

**Comment by dandriscoll** [comment]
@snbuchholz , this change is only for webchat. Can you send your bot ID?

**Comment by pandubalraj** [comment]
Hi @dandriscoll,

I am still facing this issue in webchat. 
Is this fixed ?

Thanks

**Comment by snbuchholz** [comment]
@dandriscoll ID is 943d58f3-2f89-477e-8f1a-41e9b3281d7b

**Comment by dandriscoll** [comment]
Hi @pandubalraj, @rohanar, and @snbuchholz, the issue was fixed earlier today.

Please force-refresh the web chat control and see if the problem recurs.

**Comment by pandubalraj** [comment]
Hi @dandriscoll,
I am not getting the issue right now. Thank you very much.

**Comment by rohanar** [comment]
Hi @dandriscoll 
Just tried it today (I was on holiday last week), and it looks ok now.
Thanks for fixing the issue(s).
